name: nix
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-cleanup:
    runs-on: [sdk-self-hosted-linux-amd64-build-system]
    steps:
      - name: Set up Nix
        run: echo "PATH=$PATH:/nix/var/nix/profiles/default/bin" >> $GITHUB_ENV
      - name: Cleanup the Nix store
        run: |
          nix-store --optimise
          nix-store --gc --print-dead

